version: '2'

services:
    db:
        image: mysql
        ports:
            - 3306:3306
        volumes:
            - "./.data/db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    adminer:
        image: adminer
        ports:
            - 8085:8080
    php:
        build: php7-fpm
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/catalogue/api
            - ${SYMFONY_WBI_USER_PATH}:/var/www/wbi-user
            - ${SYMFONY_TEST_PATH}:/var/www/test
#            - ./logs/symfony:/var/www/symfony/app/logs
    nginx:
        build: nginx
        ports:
            - 80:80
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx
        environment:
            - VIRTUAL_HOST=majdi.dev,majdi-user.dev
        extra_hosts:
            - majdi-user.dev:127.0.0.1
            - majdi.dev:127.0.0.1
    elk:
        image: willdurand/elk
        ports:
            - 81:80
        volumes:
            - ./elk/logstash:/etc/logstash
            - ./elk/logstash/patterns:/opt/logstash/patterns
        volumes_from:
            - php
            - nginx
